<?php

/**
 * @file
 * Contains prevnext.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Url;
use \Drupal\Core\Cache\Cache;

/**
 * Implements hook_help().
 */
function prevnext_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the prevnext module.
    case 'help.page.prevnext':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add a &quot;Previous/Next&quot; links to the node display.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function prevnext_theme($existing, $type, $theme, $path) {
  $themes = [];

  $themes['prevnext'] = [
    'variables' => [
      'direction' => '',
      'text' => '',
      'nid' => '',
      'url' => '',
      'void' => TRUE,
    ],
    // Note that there is no need to indicate the template name, in absence of
    // it the system will assume "prevnext.html.twig".
  ];

  return $themes;
}

/**
 * Implements hook_entity_extra_field_info().
 */
function prevnext_entity_extra_field_info() {
  $extra = [];

  $config = \Drupal::config('prevnext.settings');
  $enabled_nodetypes = $config->get('prevnext_enabled_nodetypes');

  if (!empty($enabled_nodetypes)) {
    foreach ($enabled_nodetypes as $bundle_key => $bundle_name) {
      $extra['node'][$bundle_key]['display']['prevnext_previous'] = [
        'label' => t('Previous'),
        'description' => t('Previous node indicator'),
        'weight' => 50,
      ];
      $extra['node'][$bundle_key]['display']['prevnext_next'] = [
        'label' => t('Next'),
        'description' => t('Next node indicator'),
        'weight' => 50,
      ];
    }
  }

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function prevnext_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  $nids = [
    'prev' => array_rand(array('', '1', '2')),
    'next' => array_rand(array('', '3', '4')),
  ];
  if ($display->getComponent('prevnext_previous')) {
    $build['prevnext_previous'] = [
      '#theme' => 'prevnext',
      '#direction' => 'previous',
      '#text' => t('Previous'),
      '#nid' => $nids['prev'],
      '#url' => Url::fromUserInput('/node/' . $nids['prev'], ['absolute' => TRUE])->toString(),
      '#void' => empty($nids['prev']),
    ];
    $build['prevnext_next'] = [
      '#theme' => 'prevnext',
      '#direction' => 'next',
      '#text' => t('Next'),
      '#nid' => $nids['next'],
      '#url' => Url::fromUserInput('/node/' . $nids['next'], ['absolute' => TRUE])->toString(),
      '#void' => empty($nids['next']),
    ];
    // Once these links will be cached inside the node rendered output, we will
    // add a custom cache tag to allow invalidation of all these cached info
    // later (for example when a new node of this type is created).
    $bundle = $entity->bundle();
    $build['#cache']['tags'][] = 'prevnext-' . $bundle;
  }

}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function prevnext_node_presave(Drupal\Core\Entity\EntityInterface $entity) {
  $config = \Drupal::config('prevnext.settings');
  $enabled_nodetypes = $config->get('prevnext_enabled_nodetypes');
  if (in_array($entity->bundle(), $enabled_nodetypes)) {
    // We are saving a node of a type with prevnext enabled, so invalidate
    // all cached rendered output of other nodes of this type with our tag.
    Cache::invalidateTags(['prevnext-' . $entity->bundle()]);
  }
}
